sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t stephengrider/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true stephengrider/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: 'us-east-1'
  app: 'dockeraws'
  env: 'docker-env'
  bucket_name: 'elasticbeanstalk-us-east-1-448045690849'
  bucket_path: 'dockeraws'
  on:
    branch: master
    access_key_id: $aws_key
    secret_access_key:
          secure: "aws_secret_key"
